### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by nagypup** [kmille/deezer-downloader#142]
![Image](https://github.com/user-attachments/assets/eecbd848-c612-4068-ad22-2d11a74a4720)

Greetings, 

with highly appreciate your effort on develop this tool for us, let me raise my hand on an issue I'm facing recently: 

(I tried to attach screenshot too, I'm not sure it's uploaded, so here is the text)

Queue
Description 	Args 	State
Downloading track	"{'track_id': 74469533, 'add_to_playlist': False}"	failed
Index out of range

So, this 'Index out of range' appears many times, even if I download track, album or zip - however inside the deezer.com site I can play the song or  album.

Would you be so kind to reflect, is it my issue (maybe some update was downloaded) or a real issue.

Kind regards: 
Ferenc

**Comment by kmille** [comment]
Hey,
I can not reproduce:

```
User request: /download with {'type': 'track', 'music_id': 74469533, 'add_to_playlist': False, 'create_zip': False}
127.0.0.1 - - [15/Mar/2025 17:59:56] "POST /download HTTP/1.1" 200 -
Downloading 'Big Joe Turner - Sk Blues (Ver 1).mp3'
Dowload finished: /tmp/deezer-downloader/songs/Big Joe Turner - Sk Blues (Ver 1).mp3
```

> Downloading track	"{'track_id': 74469533, 'add_to_playlist': False}"	mission accomplished

Which version do you use? Do you use latest version?

**Comment by nagypup** [comment]
Greetings kmille !

First of all : I do appreciate having your response on my issue !

This is the version information:
[image: image.png]

I'm on Ubuntu 24.04
I have premium membership to download flac quality (works pretty well too)

Having same shoes, please try this album

https://www.deezer.com/us/album/587755812

[image: image.png]
Here is the complete copy of terminal screen
========================================================================================================================================
***@***.***:~$ deezer-downloader --config config.ini
Listening on 127.0.0.1:5000
WARNING:waitress.queue:Task queue depth is 1
WARNING:waitress.queue:Task queue depth is 2
WARNING:waitress.queue:Task queue depth is 1
WARNING:waitress.queue:Task queue depth is 2
User request: /search with {'type': 'album', 'query': 'Blue Notes III, Vol.
8  Thad Jones, Hank Mobley'}
User request: /download with {'type': 'album', 'music_id': 587755812,
'add_to_playlist': False, 'create_zip': True}
Downloading '01 - Thad Jones April In Paris.flac'
Dowload finished: /tmp/deezer-downloader/albums/Thad Jones - Blue Notes
III, Vol. 8/01 - Thad Jones April In Paris.flac
Downloading '02 - Thad Jones Billie-Doo.flac'
Could not download song (https://www.deezer.com/us/track/2805666252). Maybe
it's not available anymore or at least not in your country. list index out
of range
Warning: list index out of range. Continuing with album...
Downloading '03 - Thad Jones If I Love Again.flac'
Could not download song (https://www.deezer.com/us/track/2805666262). Maybe
it's not available anymore or at least not in your country. list index out
of range
Warning: list index out of range. Continuing with album...
Downloading '04 - Thad Jones If Someone Had Told Me.flac'
Could not download song (https://www.deezer.com/us/track/2805666272). Maybe
it's not available anymore or at least not in your country. list index out
of range
Warning: list index out of range. Continuing with album...
Downloading '05 - Thad Jones Thedia.flac'
Could not download song (https://www.deezer.com/us/track/2805666282). Maybe
it's not available anymore or at least not in your country. list index out
of range
Warning: list index out of range. Continuing with album...
Downloading '06 - Hank Mobley High and Flighty.flac'
Dowload finished: /tmp/deezer-downloader/albums/Hank Mobley - Blue Notes
III, Vol. 8/06 - Hank Mobley High and Flighty.flac
Downloading '07 - Hank Mobley Speak Low.flac'
Could not download song (https://www.deezer.com/us/track/2805666302). Maybe
it's not available anymore or at least not in your country. list index out
of range
Warning: list index out of range. Continuing with album...
Downloading '08 - Hank Mobley Peckin' Time.flac'
Could not download song (https://www.deezer.com/us/track/2805666312). Maybe
it's not available anymore or at least not in your country. list index out
of range
Warning: list index out of range. Continuing with album...
Downloading '09 - Hank Mobley Stretchin' Out.flac'
Dowload finished: /tmp/deezer-downloader/albums/Hank Mobley - Blue Notes
III, Vol. 8/09 - Hank Mobley Stretchin' Out.flac
Downloading '10 - Hank Mobley Git-Go Blues.flac'
Could not download song (https://www.deezer.com/us/track/2805666332). Maybe
it's not available anymore or at least not in your country. list index out
of range
Warning: list index out of range. Continuing with album...
Creating zip file '/tmp/deezer-downloader/zips/Thad Jones - Blue Notes III,
Vol. 8.zip'
Adding song /tmp/deezer-downloader/albums/Thad Jones - Blue Notes III, Vol.
8/01 - Thad Jones April In Paris.flac
Adding song /tmp/deezer-downloader/albums/Hank Mobley - Blue Notes III,
Vol. 8/06 - Hank Mobley High and Flighty.flac
Adding song /tmp/deezer-downloader/albums/Hank Mobley - Blue Notes III,
Vol. 8/09 - Hank Mobley Stretchin' Out.flac
Done with the zip
========================================================================================================================================

And here is what I got:

[image: image.png]
Sorry for long speach, but I hope it's more clear.

Regards
Frank

**Comment by kmille** [comment]
Hey,
can you show me the version of `deezer-downloader --version`? I think it's out of date. Plase run `pip install -U deezer-downloader` to update.

**Comment by nagypup** [comment]
Greetings kmille !

As I saw the email reply doesn't show the screenshot capture on Github
reply.
Okay, so, the deezer version was 2.2.0 - you're right it's outdated,
because of the recommended solution worked on upgrade:

=========================================================
$ pipx install deezer-downloader --force
Installing to existing venv 'deezer-downloader'
  installed package deezer-downloader 2.3.0, installed using Python 3.12.3
  These apps are now globally available
    - deezer-downloader
done! ✨ 🌟 ✨
=========================================================

But after that, the test album didn't downloaded, so the problem still
exists.

=========================================================
WARNING:waitress.queue:Task queue depth is 1
User request: /search with {'type': 'album', 'query': 'Blue Notes III, Vol.
8  Thad Jones, Hank Mobley'}
User request: /download with {'type': 'album', 'music_id': 587755812,
'add_to_playlist': False, 'create_zip': True}
Downloading '01 - Thad Jones April In Paris.flac'
Dowload finished: /tmp/deezer-downloader/albums/Thad Jones - Blue Notes
III, Vol. 8/01 - Thad Jones April In Paris.flac
Downloading '02 - Thad Jones Billie-Doo.flac'
Could not download song (https://www.deezer.com/us/track/2805666252). Maybe
it's not available anymore or at least not in your country. list index out
of range
Warning: list index out of range. Continuing with album...
Downloading '03 - Thad Jones If I Love Again.flac'
Could not download song (https://www.deezer.com/us/track/2805666262). Maybe
it's not available anymore or at least not in your country. list index out
of range
Warning: list index out of range. Continuing with album...
Downloading '04 - Thad Jones If Someone Had Told Me.flac'
Could not download song (https://www.deezer.com/us/track/2805666272). Maybe
it's not available anymore or at least not in your country. list index out
of range
Warning: list index out of range. Continuing with album...
Downloading '05 - Thad Jones Thedia.flac'
Could not download song (https://www.deezer.com/us/track/2805666282). Maybe
it's not available anymore or at least not in your country. list index out
of range
Warning: list index out of range. Continuing with album...
Downloading '06 - Hank Mobley High and Flighty.flac'
Dowload finished: /tmp/deezer-downloader/albums/Hank Mobley - Blue Notes
III, Vol. 8/06 - Hank Mobley High and Flighty.flac
Downloading '07 - Hank Mobley Speak Low.flac'
Could not download song (https://www.deezer.com/us/track/2805666302). Maybe
it's not available anymore or at least not in your country. list index out
of range
Warning: list index out of range. Continuing with album...
Downloading '08 - Hank Mobley Peckin' Time.flac'
Could not download song (https://www.deezer.com/us/track/2805666312). Maybe
it's not available anymore or at least not in your country. list index out
of range
Warning: list index out of range. Continuing with album...
Downloading '09 - Hank Mobley Stretchin' Out.flac'
Dowload finished: /tmp/deezer-downloader/albums/Hank Mobley - Blue Notes
III, Vol. 8/09 - Hank Mobley Stretchin' Out.flac
Downloading '10 - Hank Mobley Git-Go Blues.flac'
Could not download song (https://www.deezer.com/us/track/2805666332). Maybe
it's not available anymore or at least not in your country. list index out
of range
Warning: list index out of range. Continuing with album...
Creating zip file '/tmp/deezer-downloader/zips/Thad Jones - Blue Notes III,
Vol. 8.zip'
Adding song /tmp/deezer-downloader/albums/Thad Jones - Blue Notes III, Vol.
8/01 - Thad Jones April In Paris.flac
Adding song /tmp/deezer-downloader/albums/Hank Mobley - Blue Notes III,
Vol. 8/06 - Hank Mobley High and Flighty.flac
Adding song /tmp/deezer-downloader/albums/Hank Mobley - Blue Notes III,
Vol. 8/09 - Hank Mobley Stretchin' Out.flac
Done with the zip
=========================================================

With regards
Frank

**Comment by kmille** [comment]
As I said: `pip install -U deezer-downloader`. You missed the `-U`. You re-installed the current version.
